repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    -   id: go-fmt
    -   id: go-build-mod
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.54.1
    hooks:
    -   id: golangci-lint
        entry: golangci-lint run
